# version: "3.7"
services:
  # image project
  micro_application:
    build:
      args:
        user: milena
        uid: 1000
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - micro_application_network

  # nginx
  micro_application_nginx:
    image: nginx:alpine
    ports:
      - "8484:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - micro_application_network

  # db mysql
  db_micro_application:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3434:3306"
    networks:
      - micro_application_network

networks:
  micro_application_network:
    driver: bridge
